import { OpeningTrap } from "@/types/trap";

export const FAMOUS_TRAPS: OpeningTrap[] = [
  {
    id: "legals-trap",
    name: "Légal's Mate",
    openingName: "Italian Game",
    eco: "C41",
    side: "white",
    difficulty: "Beginner",
    description: "A legendary queen sacrifice in the Italian Game leading to a stunning knight and bishop checkmate on f7.",
    punishmentExplanation: "If Black greedily captures White's unprotected queen with 5...Bxd1??, White delivers checkmate with 6.Bxf7+ Ke7 7.Nd5#!",
    moves: ["e4", "e5", "Nf3", "d6", "Bc4", "Bg4", "Nc3", "g6", "Nxe5", "Bxd1", "Bxf7+", "Ke7", "Nd5#"],
    steps: [
      { moveSan: "e4", explanation: "White opens with the King's Pawn." },
      { moveSan: "e5", explanation: "Black responds symmetrically." },
      { moveSan: "Nf3", explanation: "White develops the knight attacking e5." },
      { moveSan: "d6", explanation: "Black defends with the Philidor Defense." },
      { moveSan: "Bc4", explanation: "White targets the weak f7 square." },
      { moveSan: "Bg4", explanation: "Black pins White's knight to the queen." },
      { moveSan: "Nc3", explanation: "White continues natural development." },
      { moveSan: "g6", explanation: "Black prepares to fianchetto, but neglects central king safety." },
      { moveSan: "Nxe5", isCriticalStep: true, explanation: "CRITICAL MOVE! White sacrifces the Queen on d1! If Black takes with 9...Bxd1??, White mates in two." },
      { moveSan: "Bxd1", explanation: "Black falls into the trap and greedily captures the Queen!" },
      { moveSan: "Bxf7+", explanation: "White checks the King, forcing it to e7." },
      { moveSan: "Ke7", explanation: "Black's King is forced to e7." },
      { moveSan: "Nd5#", isCriticalStep: true, explanation: "CHECKMATE! The two knights and bishop deliver a beautiful checkmate pattern!" },
    ],
  },
  {
    id: "noahs-ark-trap",
    name: "Noah's Ark Trap",
    openingName: "Ruy Lopez",
    eco: "C88",
    side: "black",
    difficulty: "Intermediate",
    description: "A famous trap in the Ruy Lopez where Black traps White's light-squared bishop on b3 using pawn pushes a6, b5, and c4.",
    punishmentExplanation: "White loses a full piece on b3 after Black's pawn push c4 traps the bishop with nowhere to escape.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "d6", "d4", "b5", "Bb3", "Nxd4", "Nxd4", "exd4", "Qxd4", "c5", "Qd5", "Be6", "Qc6+", "Bd7", "Qd5", "c4"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bb5", explanation: "Ruy Lopez opening." },
      { moveSan: "a6", explanation: "Morphy Defense forcing the bishop back." },
      { moveSan: "Ba4", explanation: "White retreats the bishop." },
      { moveSan: "d6", explanation: "Black prepares to push b5." },
      { moveSan: "d4", explanation: "White strikes in the center." },
      { moveSan: "b5", explanation: "Black expands on the queenside." },
      { moveSan: "Bb3", explanation: "White's bishop retreats to b3." },
      { moveSan: "Nxd4", explanation: "Black exchanges knights on d4." },
      { moveSan: "Nxd4", explanation: "White recaptures." },
      { moveSan: "exd4", explanation: "Black recaptures." },
      { moveSan: "Qxd4", isCriticalStep: true, explanation: "White recaptures with the Queen, but leaves the bishop susceptible to pawn pushes." },
      { moveSan: "c5", explanation: "Black attacks White's queen." },
      { moveSan: "Qd5", explanation: "White threatens a mate/rook fork on f7 & a8." },
      { moveSan: "Be6", explanation: "Black comfortably blocks." },
      { moveSan: "Qc6+", explanation: "White checks." },
      { moveSan: "Bd7", explanation: "Black blocks again." },
      { moveSan: "Qd5", explanation: "White's queen retreats." },
      { moveSan: "c4", isCriticalStep: true, explanation: "TRAPPED! Black pushes c4 and White's light-squared bishop on b3 has no escape squares!" },
    ],
  },
  {
    id: "stafford-gambit-trap",
    name: "Stafford Gambit Trap",
    openingName: "Petrov's Defense",
    eco: "C42",
    side: "black",
    difficulty: "Beginner",
    description: "An aggressive trap for Black involving rapid piece development and devastating tactical sacrifices against White's king.",
    punishmentExplanation: "White's kingside crumbles under Black's Ng4, Bc5, and Qh4 battery targeting f2 and h2.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Bg5", "Nxe4", "Bxd8", "Bxf2+", "Ke2", "Bg4#"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nf6", explanation: "Petrov's Defense." },
      { moveSan: "Nxe5", explanation: "White captures on e5." },
      { moveSan: "Nc6", isCriticalStep: true, explanation: "Stafford Gambit! Black sacrifices a pawn for rapid piece development." },
      { moveSan: "Nxc6", explanation: "White accepts the knight trade." },
      { moveSan: "dxc6", explanation: "Black recaptures toward the center." },
      { moveSan: "d3", explanation: "White solidifies the e4 pawn." },
      { moveSan: "Bc5", explanation: "Black aims at f2." },
      { moveSan: "Bg5", explanation: "White pins Black's f6 knight." },
      { moveSan: "Nxe4!", isCriticalStep: true, explanation: "TACTICAL SACRIFICE! Black ignores the pin and sacrfices the Queen!" },
      { moveSan: "Bxd8", explanation: "White greedily accepts the Queen." },
      { moveSan: "Bxf2+", explanation: "Black checks on f2." },
      { moveSan: "Ke2", explanation: "White's King is forced to e2." },
      { moveSan: "Bg4#", isCriticalStep: true, explanation: "CHECKMATE! Black delivers checkmate with the light-squared bishop!" },
    ],
  },
  {
    id: "elephant-trap",
    name: "Elephant Trap",
    openingName: "Queen's Gambit Declined",
    eco: "D51",
    side: "black",
    difficulty: "Intermediate",
    description: "A subtle trap in the Queen's Gambit Declined where White attempts to win a pawn on d5 but loses a piece on d5.",
    punishmentExplanation: "If White plays 6.Nxd5?? thinking the c6 knight is pinned, Black plays 6...Nxd5! 7.Bxd8 Bb4+ winning White's queen back with an extra piece!",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Nbd7", "cxd5", "exd5", "Nxd5", "Nxd5", "Bxd8", "Bb4+", "Qd2", "Bxd2+", "Kxd2", "Kxd8"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn opening." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "c4", explanation: "Queen's Gambit." },
      { moveSan: "e6", explanation: "Queen's Gambit Declined." },
      { moveSan: "Nc3", explanation: "White develops Nc3." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "Bg5", explanation: "White pins Nf6." },
      { moveSan: "Nbd7", isCriticalStep: true, explanation: "The trap is set! Black sets a trap by developing Nbd7, appearing to leave d5 pinned." },
      { moveSan: "cxd5", explanation: "White takes on d5." },
      { moveSan: "exd5", explanation: "Black recaptures." },
      { moveSan: "Nxd5", isCriticalStep: true, explanation: "BLUNDER! White thinks d5 is pinned and captures the pawn." },
      { moveSan: "Nxd5!", explanation: "Black ignores the pin on the queen!" },
      { moveSan: "Bxd8", explanation: "White takes Black's queen." },
      { moveSan: "Bb4+", isCriticalStep: true, explanation: "FORCED QUEEN RECOVERY! Bb4+ forces Qd2." },
      { moveSan: "Qd2", explanation: "White is forced to block with the queen." },
      { moveSan: "Bxd2+", explanation: "Black takes White's queen." },
      { moveSan: "Kxd2", explanation: "White recaptures with the King." },
      { moveSan: "Kxd8", explanation: "Black recaptures the bishop on d8 and remains up a full piece!" },
    ],
  },
  {
    id: "lasker-trap",
    name: "Lasker Trap",
    openingName: "Albin Countergambit",
    eco: "D08",
    side: "black",
    difficulty: "Advanced",
    description: "A brilliant underpromotion trap in the Albin Countergambit featuring an underpromotion to a Knight with check on move 7!",
    punishmentExplanation: "7...fxg1=N+! promotes to a Knight with check, preventing White from trading queens and winning material.",
    moves: ["d4", "d5", "c4", "e5", "dxe5", "d4", "e3", "Bb4+", "Bd2", "dxe3", "Bxb4", "exf2+", "Ke2", "fxg1=N+", "Rxg1", "Bg4+"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "c4", explanation: "Queen's Gambit." },
      { moveSan: "e5", explanation: "Albin Countergambit!" },
      { moveSan: "dxe5", explanation: "White takes on e5." },
      { moveSan: "d4", explanation: "Black advances the d-pawn to d4." },
      { moveSan: "e3", explanation: "White tries to challenge d4." },
      { moveSan: "Bb4+", explanation: "Black checks on b4." },
      { moveSan: "Bd2", explanation: "White blocks with the bishop." },
      { moveSan: "dxe3", isCriticalStep: true, explanation: "Black sacrifices the bishop on b4!" },
      { moveSan: "Bxb4", explanation: "White greedily captures the bishop." },
      { moveSan: "exf2+", explanation: "Black checks on f2!" },
      { moveSan: "Ke2", explanation: "White's King steps to e2." },
      { moveSan: "fxg1=N+", isCriticalStep: true, explanation: "UNDERPROMOTION TO KNIGHT WITH CHECK! Promoting to Knight checks the King first!" },
      { moveSan: "Rxg1", explanation: "White's rook captures the knight." },
      { moveSan: "Bg4+", isCriticalStep: true, explanation: "QUEEN FORK! Black pins and wins White's queen!" },
    ],
  },
  {
    id: "fishing-pole-trap",
    name: "Fishing Pole Trap",
    openingName: "Ruy Lopez",
    eco: "C65",
    side: "black",
    difficulty: "Intermediate",
    description: "An aggressive trap for Black involving an unprovoked knight leap ng4 and h5 pawn sacrifice opening the h-file for checkmate.",
    punishmentExplanation: "White opens the h-file by capturing hxg4, allowing Black's rook to swarm the h-file with Qh4 and quick mate.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "Ng4", "h3", "h5", "hxg4", "hxg4", "Ne1", "Qh4", "f3", "g3"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bb5", explanation: "Ruy Lopez." },
      { moveSan: "Nf6", explanation: "Berlin Defense." },
      { moveSan: "O-O", explanation: "White castles." },
      { moveSan: "Ng4", isCriticalStep: true, explanation: "Fishing Pole setup! Black leaps Ng4 inviting White to kick it with h3." },
      { moveSan: "h3", explanation: "White bites the bait and plays h3." },
      { moveSan: "h5", isCriticalStep: true, explanation: "Black defends the knight with h5, sacrificing the piece!" },
      { moveSan: "hxg4", explanation: "White captures the knight, opening the h-file." },
      { moveSan: "hxg4", explanation: "Black recaptures, opening the h-file for the h8 rook." },
      { moveSan: "Ne1", explanation: "White retreats the knight." },
      { moveSan: "Qh4", isCriticalStep: true, explanation: "Black's queen infiltrates on h4 threatening mate on h1!" },
      { moveSan: "f3", explanation: "White tries to make an escape square for the king." },
      { moveSan: "g3", isCriticalStep: true, explanation: "SEALED! Black plays g3, blocking the escape square and sealing White's king for mate on h1!" },
    ],
  },
  {
    id: "blackburne-shilling-gambit",
    name: "Blackburne Shilling Gambit",
    openingName: "Italian Game",
    eco: "C50",
    side: "black",
    difficulty: "Beginner",
    description: "A famous trap where Black offers an undefended pawn on e5, leading to a smothered mate or queen capture on c2.",
    punishmentExplanation: "White's greedy 4.Nxe5?? falls into 4...Qg5! threatening g2, e4, and f2.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nd4", "Nxe5", "Qg5", "Nxf7", "Qxg2", "Rf1", "Qxe4+", "Be2", "Nf3#"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black plays Nc6." },
      { moveSan: "Bc4", explanation: "Italian Game." },
      { moveSan: "Nd4", isCriticalStep: true, explanation: "Black gambits e5 by moving Nd4!" },
      { moveSan: "Nxe5", explanation: "GREEDY BLUNDER! White takes the pawn on e5." },
      { moveSan: "Qg5", isCriticalStep: true, explanation: "COUNTERATTACK! Black attacks both the e5 knight and g2 pawn." },
      { moveSan: "Nxf7", explanation: "White forks Black's queen and rook." },
      { moveSan: "Qxg2", explanation: "Black takes g2, threatening White's rook." },
      { moveSan: "Rf1", explanation: "White saves the rook." },
      { moveSan: "Qxe4+", explanation: "Black checks on e4." },
      { moveSan: "Be2", explanation: "White blocks with the bishop." },
      { moveSan: "Nf3#", isCriticalStep: true, explanation: "SMOTHERED MATE! The knight on f3 delivers a beautiful smothered checkmate!" },
    ],
  },
  {
    id: "siberian-trap",
    name: "Siberian Trap",
    openingName: "Smith-Morra Gambit",
    eco: "B21",
    side: "black",
    difficulty: "Intermediate",
    description: "A deadly trap in the Sicilian Defense Smith-Morra Gambit leading to a queen-trapping checkmate pattern on h2.",
    punishmentExplanation: "White plays Bc4 and h3, allowing Black's Nd4 and Qc7 to threaten mate on h2 while trapping White's queen.",
    moves: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6", "Nf3", "e6", "Bc4", "Qc7", "O-O", "Nf6", "Qe2", "Ng4", "h3", "Nd4"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn." },
      { moveSan: "c5", explanation: "Sicilian Defense." },
      { moveSan: "d4", explanation: "Smith-Morra Gambit." },
      { moveSan: "cxd4", explanation: "Black accepts." },
      { moveSan: "c3", explanation: "White offers c-pawn." },
      { moveSan: "dxc3", explanation: "Black accepts." },
      { moveSan: "Nxc3", explanation: "White develops." },
      { moveSan: "Nc6", explanation: "Black develops." },
      { moveSan: "Nf3", explanation: "White develops." },
      { moveSan: "e6", explanation: "Black solidifies." },
      { moveSan: "Bc4", explanation: "White targets f7." },
      { moveSan: "Qc7", explanation: "Black prepares battery." },
      { moveSan: "O-O", explanation: "White castles." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "Qe2", explanation: "White moves queen." },
      { moveSan: "Ng4", explanation: "Black leaps Ng4." },
      { moveSan: "h3", explanation: "White kicks the knight with h3." },
      { moveSan: "Nd4", isCriticalStep: true, explanation: "DEVASTATING KNIGHT SACRIFICE! Nd4 attacks White's queen on e2 and threatens Nxf3+ followed by Qh2#!" },
    ],
  },
  {
    id: "englund-gambit-trap",
    name: "Englund Gambit Trap",
    openingName: "Englund Gambit",
    eco: "A40",
    side: "black",
    difficulty: "Beginner",
    description: "A fast tactical trap for Black against 1.d4 leading to a back-rank queen checkmate on c1.",
    punishmentExplanation: "White attempts to defend b2 with 6.Bc3??, allowing 6...Bb4! 7.Qd2 Bxc3 8.Qxc3 Qc1#!",
    moves: ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Bc3", "Bb4", "Qd2", "Bxc3", "Qxc3", "Qc1#"],
    steps: [
      { moveSan: "d4", explanation: "White plays 1.d4." },
      { moveSan: "e5", explanation: "Englund Gambit!" },
      { moveSan: "dxe5", explanation: "White accepts." },
      { moveSan: "Nc6", explanation: "Black attacks e5." },
      { moveSan: "Nf3", explanation: "White defends e5." },
      { moveSan: "Qe7", explanation: "Black doubles attack on e5." },
      { moveSan: "Bf4", explanation: "White defends e5." },
      { moveSan: "Qb4+", isCriticalStep: true, explanation: "QUEEN FORK! Checking the king and attacking b2 & f4!" },
      { moveSan: "Bd2", explanation: "White blocks check." },
      { moveSan: "Qxb2", explanation: "Black captures on b2." },
      { moveSan: "Bc3", explanation: "White defends the a1 rook." },
      { moveSan: "Bb4", isCriticalStep: true, explanation: "PIN! Black pins the c3 bishop to White's king!" },
      { moveSan: "Qd2", explanation: "White defends c3." },
      { moveSan: "Bxc3", explanation: "Black trades on c3." },
      { moveSan: "Qxc3", explanation: "White recaptures." },
      { moveSan: "Qc1#", isCriticalStep: true, explanation: "CHECKMATE! Back-rank checkmate on c1!" },
    ],
  },
  {
    id: "kieninger-trap",
    name: "Kieninger Trap",
    openingName: "Budapest Gambit",
    eco: "A52",
    side: "black",
    difficulty: "Intermediate",
    description: "A famous smothered mate trap in the Budapest Gambit ending with 8...Nd3#.",
    punishmentExplanation: "White plays 8.axb4?? expecting Black to lose a piece, but Black delivers a beautiful smothered checkmate with 8...Nd3#!",
    moves: ["d4", "Nf6", "c4", "e5", "dxe5", "Ng4", "Bf4", "Nc6", "Nf3", "Bb4+", "Nbd2", "Qe7", "a3", "Ngxe5", "axb4", "Nd3#"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn." },
      { moveSan: "Nf6", explanation: "Indian Defense." },
      { moveSan: "c4", explanation: "White pushes c4." },
      { moveSan: "e5", explanation: "Budapest Gambit!" },
      { moveSan: "dxe5", explanation: "White accepts." },
      { moveSan: "Ng4", explanation: "Black attacks e5." },
      { moveSan: "Bf4", explanation: "White defends." },
      { moveSan: "Nc6", explanation: "Black attacks e5 again." },
      { moveSan: "Nf3", explanation: "White defends." },
      { moveSan: "Bb4+", explanation: "Black checks on b4." },
      { moveSan: "Nbd2", explanation: "White blocks with Nbd2." },
      { moveSan: "Qe7", explanation: "Black attacks e5 a 3rd time." },
      { moveSan: "a3", explanation: "White kicks the bishop." },
      { moveSan: "Ngxe5", isCriticalStep: true, explanation: "TRAP SET! Black ignores the bishop and captures e5!" },
      { moveSan: "axb4", explanation: "GREEDY BLUNDER! White captures the bishop on b4." },
      { moveSan: "Nd3#", isCriticalStep: true, explanation: "SMOTHERED MATE! Nd3# checkmates White's king trapped by its own pawns!" },
    ],
  },
  {
    id: "mortimer-trap",
    name: "Mortimer Trap",
    openingName: "Ruy Lopez",
    eco: "C65",
    side: "white",
    difficulty: "Intermediate",
    description: "A clever counter-trap in the Berlin Ruy Lopez where White delivers a smothered mate with Nc4 and Nd6#.",
    punishmentExplanation: "If Black greedily plays 6...cxb5??, White mates with 7.Nd6#!",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "d3", "Ne7", "Nxe5", "c6", "Nc4", "cxb5", "Nd6#"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bb5", explanation: "Ruy Lopez." },
      { moveSan: "Nf6", explanation: "Berlin Defense." },
      { moveSan: "d3", explanation: "White solidifies e4." },
      { moveSan: "Ne7", explanation: "Mortimer Trap setup! Black leaves e5 undefended." },
      { moveSan: "Nxe5", explanation: "White captures e5." },
      { moveSan: "c6", explanation: "Black attacks the bishop on b5." },
      { moveSan: "Nc4", isCriticalStep: true, explanation: "COUNTER TRAP! White moves Nc4 threatening Nd6# smothered mate!" },
      { moveSan: "cxb5", explanation: "BLUNDER! Black captures the bishop, ignoring the smothered mate threat." },
      { moveSan: "Nd6#", isCriticalStep: true, explanation: "SMOTHERED MATE! White checkmates Black on d6!" },
    ],
  },
  {
    id: "fried-liver-attack",
    name: "Fried Liver Attack Trap",
    openingName: "Italian Game",
    eco: "C57",
    side: "white",
    difficulty: "Beginner",
    description: "An aggressive knight sacrifice on f7 forcing Black's king to walk into the open center under attack.",
    punishmentExplanation: "White sacrifices Nxf7, exposing Black's King to Qf3+ and Nc3 central pressure.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bc4", explanation: "Italian Game." },
      { moveSan: "Nf6", explanation: "Two Knights Defense." },
      { moveSan: "Ng5", explanation: "White targets f7." },
      { moveSan: "d5", explanation: "Black blocks with d5." },
      { moveSan: "exd5", explanation: "White captures on d5." },
      { moveSan: "Nxd5", isCriticalStep: true, explanation: "Black recaptures with knight (Na5 is safer)." },
      { moveSan: "Nxf7", isCriticalStep: true, explanation: "KNIGHT SACRIFICE! White sacrifices on f7 forking Queen and Rook." },
      { moveSan: "Kxf7", explanation: "Black captures the knight." },
      { moveSan: "Qf3+", explanation: "White checks and attacks the d5 knight." },
      { moveSan: "Ke6", explanation: "Black's King is forced to e6 to defend d5." },
      { moveSan: "Nc3", explanation: "White piles pressure on the pinned d5 knight!" },
    ],
  },
  {
    id: "lasker-trap",
    name: "Lasker Trap",
    openingName: "Albin Countergambit",
    eco: "D08",
    side: "black",
    difficulty: "Advanced",
    description: "A brilliant underpromotion tactic for Black in the Albin Countergambit featuring 7...fxg1=N+! check before winning White's queen.",
    punishmentExplanation: "White plays 6.Bxb4?? allowing 6...exf2+ 7.Ke2 fxg1=N+! with check, preventing White from trading queens with Qxd8+ and winning a full piece.",
    moves: ["d4", "d5", "c4", "e5", "dxe5", "d4", "e3", "Bb4+", "Bd2", "dxe3", "Bxb4", "exf2+", "Ke2", "fxg1=N+", "Rxg1", "Bg4+"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn opening." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "c4", explanation: "Queen's Gambit." },
      { moveSan: "e5", explanation: "Albin Countergambit!" },
      { moveSan: "dxe5", explanation: "White captures e5." },
      { moveSan: "d4", explanation: "Black pushes d4 seizing space." },
      { moveSan: "e3", explanation: "White attacks d4." },
      { moveSan: "Bb4+", explanation: "Black checks on b4." },
      { moveSan: "Bd2", explanation: "White blocks check." },
      { moveSan: "dxe3", isCriticalStep: true, explanation: "TRAP SET! Black ignores the b4 bishop and captures on e3!" },
      { moveSan: "Bxb4", explanation: "BLUNDER! White takes the bishop." },
      { moveSan: "exf2+", explanation: "Black checks on f2!" },
      { moveSan: "Ke2", explanation: "White moves King to e2." },
      { moveSan: "fxg1=N+", isCriticalStep: true, explanation: "UNDERPROMOTION WITH CHECK! Promoting to a Knight checks White, preventing 8.Qxd8+!" },
      { moveSan: "Rxg1", explanation: "White captures the knight." },
      { moveSan: "Bg4+", isCriticalStep: true, explanation: "QUEEN SKEWER! Black skewers White's king and queen, winning the queen!" },
    ],
  },
  {
    id: "cambridge-springs-trap",
    name: "Cambridge Springs Trap",
    openingName: "Queen's Gambit Declined",
    eco: "D52",
    side: "black",
    difficulty: "Intermediate",
    description: "A classic trap where White's early Bg5 pin backfires against Black's Qa5 and Bb4 battery.",
    punishmentExplanation: "If White plays 6.Nxd5?? expecting to win a pawn, Black responds 6...Nxd5! 7.Bxd8 Bb4+ winning White's queen back with an extra minor piece.",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Nbd7", "Nf3", "c6", "e3", "Qa5", "cxd5", "Nxd5", "Qd2", "Bb4"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn opening." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "c4", explanation: "Queen's Gambit." },
      { moveSan: "e6", explanation: "Queen's Gambit Declined." },
      { moveSan: "Nc3", explanation: "White develops Nc3." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "Bg5", explanation: "White pins the f6 knight." },
      { moveSan: "Nbd7", isCriticalStep: true, explanation: "Cambridge Springs setup! Black prepares to unpin with Qa5." },
      { moveSan: "Nf3", explanation: "White develops Nf3." },
      { moveSan: "c6", explanation: "Black solidifies the center." },
      { moveSan: "e3", explanation: "White solidifies d4." },
      { moveSan: "Qa5", isCriticalStep: true, explanation: "UNPIN & ATTACK! Black pins c3 knight and threatens Ne4!" },
      { moveSan: "cxd5", explanation: "White trades on d5." },
      { moveSan: "Nxd5", explanation: "Black recaptures with knight." },
      { moveSan: "Qd2", explanation: "White defends c3 with the queen." },
      { moveSan: "Bb4", isCriticalStep: true, explanation: "TRIPLE ATTACK! Black pins c3 with a 3rd piece, winning material!" },
    ],
  },
  {
    id: "magnus-smith-trap",
    name: "Magnus Smith Trap",
    openingName: "Sicilian Defense (Smith-Morra)",
    eco: "B21",
    side: "black",
    difficulty: "Intermediate",
    description: "A fast tactical trap in the Sicilian Defense where Black unleashes Nd4 threatening mate on h2 while trapping White's queen.",
    punishmentExplanation: "White plays 9.h3?? trying to kick Black's knight, but 9...Nd4! attacks the e2 queen while maintaining the h2 checkmate threat.",
    moves: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6", "Nf3", "e6", "Bc4", "Qc7", "O-O", "Nf6", "Qe2", "Ng4", "h3", "Nd4"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "c5", explanation: "Sicilian Defense." },
      { moveSan: "d4", explanation: "Smith-Morra Gambit." },
      { moveSan: "cxd4", explanation: "Black captures." },
      { moveSan: "c3", explanation: "White offers pawn." },
      { moveSan: "dxc3", explanation: "Black captures." },
      { moveSan: "Nxc3", explanation: "White develops knight." },
      { moveSan: "Nc6", explanation: "Black develops knight." },
      { moveSan: "Nf3", explanation: "White develops knight." },
      { moveSan: "e6", explanation: "Black solidifies." },
      { moveSan: "Bc4", explanation: "White aims at f7." },
      { moveSan: "Qc7", explanation: "Black sets up queen on c7." },
      { moveSan: "O-O", explanation: "White castles." },
      { moveSan: "Nf6", explanation: "Black develops knight." },
      { moveSan: "Qe2", explanation: "White plays Qe2." },
      { moveSan: "Ng4", isCriticalStep: true, explanation: "ATTACK SETUP! Black leaps Ng4 targeting h2." },
      { moveSan: "h3", explanation: "BLUNDER! White tries to kick the knight with h3." },
      { moveSan: "Nd4", isCriticalStep: true, explanation: "DEVASTATING KNIGHT FORK! Nd4 attacks White's queen and threatens Qh2# checkmate!" },
    ],
  },
  {
    id: "wurzburger-trap",
    name: "Würzburger Trap",
    openingName: "Vienna Game",
    eco: "C22",
    side: "black",
    difficulty: "Advanced",
    description: "A dynamic trap in the Vienna Game where Black sacrifices a knight on g3 to launch a crushing kingside onslaught.",
    punishmentExplanation: "White's kingside collapses after 6...Nxg3 7.Nf3 Qh5! winning material with heavy central piece activity.",
    moves: ["e4", "e5", "Nc3", "Nf6", "f4", "d5", "fxe5", "Nxe4", "d3", "Qh4+", "g3", "Nxg3", "Nf3", "Qh5", "Nxd5", "Bg4"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black responds symmetrically." },
      { moveSan: "Nc3", explanation: "Vienna Game." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "f4", explanation: "Vienna Gambit." },
      { moveSan: "d5", explanation: "Black strikes back in the center." },
      { moveSan: "fxe5", explanation: "White captures on e5." },
      { moveSan: "Nxe4", explanation: "Black leaps knight to e4." },
      { moveSan: "d3", explanation: "White attacks the knight." },
      { moveSan: "Qh4+", isCriticalStep: true, explanation: "QUEEN CHECK! Infiltrating the kingside dark squares." },
      { moveSan: "g3", explanation: "White blocks check with g3." },
      { moveSan: "Nxg3", isCriticalStep: true, explanation: "KNIGHT SACRIFICE! Opening the h-file for Black's attack." },
      { moveSan: "Nf3", explanation: "White attacks Black's queen." },
      { moveSan: "Qh5", explanation: "Black retreats queen to h5." },
      { moveSan: "Nxd5", explanation: "White attacks c7." },
      { moveSan: "Bg4", isCriticalStep: true, explanation: "PIN! Black pins White's knight to the queen, seizing full initiative!" },
    ],
  },
  {
    id: "monticelli-trap",
    name: "Monticelli Trap",
    openingName: "Bogo-Indian Defense",
    eco: "E11",
    side: "white",
    difficulty: "Advanced",
    description: "A famous tactical sequence played by Monticelli and Capablanca targeting Black's b7 bishop and g7 mate simultaneously.",
    punishmentExplanation: "White plays 10.Ng5! double-attacking g7 checkmate and Black's undefended bishop on b7.",
    moves: ["d4", "Nf6", "c4", "e6", "Nf3", "Bb4+", "Bd2", "Bxd2+", "Qxd2", "b6", "g3", "Bb7", "Bg2", "O-O", "Nc3", "Ne4", "Qc2", "Nxc3", "Ng5"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn opening." },
      { moveSan: "Nf6", explanation: "Indian Defense." },
      { moveSan: "c4", explanation: "White pushes c4." },
      { moveSan: "e6", explanation: "Black plays e6." },
      { moveSan: "Nf3", explanation: "White develops Nf3." },
      { moveSan: "Bb4+", explanation: "Bogo-Indian check." },
      { moveSan: "Bd2", explanation: "White blocks with bishop." },
      { moveSan: "Bxd2+", explanation: "Black trades bishops." },
      { moveSan: "Qxd2", explanation: "White recaptures with queen." },
      { moveSan: "b6", explanation: "Black prepares b7 bishop fianchetto." },
      { moveSan: "g3", explanation: "White prepares g2 bishop fianchetto." },
      { moveSan: "Bb7", explanation: "Black places bishop on long diagonal." },
      { moveSan: "Bg2", explanation: "White places bishop on long diagonal." },
      { moveSan: "O-O", explanation: "Black castles." },
      { moveSan: "Nc3", explanation: "White develops Nc3." },
      { moveSan: "Ne4", explanation: "Black posts knight on e4." },
      { moveSan: "Qc2", explanation: "White attacks e4 knight." },
      { moveSan: "Nxc3", explanation: "Black trades knights on c3." },
      { moveSan: "Ng5", isCriticalStep: true, explanation: "DOUBLE THREAT! White leaps Ng5 threatening Qg7# checkmate and attacking the b7 bishop!" },
    ],
  },
  {
    id: "halosar-trap",
    name: "Halosar Trap",
    openingName: "Blackmar-Diemer Gambit",
    eco: "D00",
    side: "white",
    difficulty: "Intermediate",
    description: "A rapid attacking trap for White in the Blackmar-Diemer Gambit ending with a queen-sacrifice or Nb5 checkmate threat.",
    punishmentExplanation: "Black plays 7...Bg4?? pinning White's queen to the rook, but White plays 8.Nb5! threatening Nc7# smothered checkmate!",
    moves: ["d4", "d5", "e4", "dxe4", "Nc3", "Nf6", "f3", "exf3", "Qxf3", "Qxd4", "Be3", "Qb4", "O-O-O", "Bg4", "Nb5"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn opening." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "e4", explanation: "Blackmar-Diemer Gambit!" },
      { moveSan: "dxe4", explanation: "Black accepts." },
      { moveSan: "Nc3", explanation: "White attacks e4." },
      { moveSan: "Nf6", explanation: "Black defends e4." },
      { moveSan: "f3", explanation: "White offers 2nd pawn." },
      { moveSan: "exf3", explanation: "Black accepts." },
      { moveSan: "Qxf3", explanation: "White recaptures with queen." },
      { moveSan: "Qxd4", explanation: "Black takes d4 pawn." },
      { moveSan: "Be3", explanation: "White attacks Black's queen." },
      { moveSan: "Qb4", explanation: "Black's queen retreats to b4." },
      { moveSan: "O-O-O", explanation: "White castles queenside." },
      { moveSan: "Bg4", isCriticalStep: true, explanation: "Black attempts pin on White's queen." },
      { moveSan: "Nb5", isCriticalStep: true, explanation: "DEVASTATING KNIGHT MOVE! White threatens Nc7# checkmate, ignoring the queen pin!" },
    ],
  },
  {
    id: "rubinstein-trap",
    name: "Rubinstein Trap",
    openingName: "Queen's Gambit Declined",
    eco: "D63",
    side: "white",
    difficulty: "Intermediate",
    description: "A positional and tactical trap named after Akiba Rubinstein where Black loses a central knight to a tactical pin.",
    punishmentExplanation: "If Black plays 11...e5??, White plays 12.Nxd5! winning a pawn or piece because Black cannot recapture without losing the queen.",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Be7", "e3", "O-O", "Nf3", "Nbd7", "Rc1", "c6", "Bd3", "dxc4", "Bxc4", "Nd5", "Bxe7", "Qxe7", "O-O", "Nxc3", "Rxc3", "e5", "Nxd5"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn opening." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "c4", explanation: "Queen's Gambit." },
      { moveSan: "e6", explanation: "Queen's Gambit Declined." },
      { moveSan: "Nc3", explanation: "White develops Nc3." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "Bg5", explanation: "White pins f6." },
      { moveSan: "Be7", explanation: "Black unpins." },
      { moveSan: "e3", explanation: "White solidifies." },
      { moveSan: "O-O", explanation: "Black castles." },
      { moveSan: "Nf3", explanation: "White develops Nf3." },
      { moveSan: "Nbd7", explanation: "Black plays Nbd7." },
      { moveSan: "Rc1", explanation: "White places rook on c-file." },
      { moveSan: "c6", explanation: "Black supports center." },
      { moveSan: "Bd3", explanation: "White develops bishop." },
      { moveSan: "dxc4", explanation: "Black takes c4." },
      { moveSan: "Bxc4", explanation: "White recaptures." },
      { moveSan: "Nd5", explanation: "Black trades knights." },
      { moveSan: "Bxe7", explanation: "White trades bishops." },
      { moveSan: "Qxe7", explanation: "Black recaptures with queen." },
      { moveSan: "O-O", explanation: "White castles." },
      { moveSan: "Nxc3", explanation: "Black trades knights." },
      { moveSan: "Rxc3", explanation: "White recaptures with rook." },
      { moveSan: "e5", isCriticalStep: true, explanation: "BLUNDER! Black tries to break in the center." },
      { moveSan: "Nxd5", isCriticalStep: true, explanation: "TACTICAL WIN! White captures on d5, winning material due to queen alignment!" },
    ],
  },
  {
    id: "sea-cadet-trap",
    name: "Sea Cadet Trap",
    openingName: "Philidor Defense",
    eco: "C41",
    side: "white",
    difficulty: "Beginner",
    description: "A classic tactical checkmate pattern in the Philidor Defense where White sacrifices the queen for a 3-piece checkmate on f7 and d5.",
    punishmentExplanation: "If Black captures White's queen with 5...Bxd1??, White mates with 6.Bxf7+ Ke7 7.Nd5#!",
    moves: ["e4", "e5", "Nf3", "d6", "Bc4", "h6", "Nc3", "Bg4", "Nxe5", "Bxd1", "Bxf7+", "Ke7", "Nd5#"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "d6", explanation: "Philidor Defense." },
      { moveSan: "Bc4", explanation: "White targets f7." },
      { moveSan: "h6", explanation: "Black plays h6." },
      { moveSan: "Nc3", explanation: "White develops Nc3." },
      { moveSan: "Bg4", explanation: "Black pins knight to queen." },
      { moveSan: "Nxe5", isCriticalStep: true, explanation: "QUEEN SACRIFICE! White captures e5 leaving queen on d1 unprotected!" },
      { moveSan: "Bxd1", explanation: "Black falls into the trap and takes the queen!" },
      { moveSan: "Bxf7+", explanation: "White checks on f7!" },
      { moveSan: "Ke7", explanation: "Black King forced to e7." },
      { moveSan: "Nd5#", isCriticalStep: true, explanation: "CHECKMATE! The two knights and bishop deliver checkmate!" },
    ],
  },
  {
    id: "tarrasch-trap",
    name: "Tarrasch Trap",
    openingName: "Ruy Lopez (Open Variation)",
    eco: "C80",
    side: "white",
    difficulty: "Intermediate",
    description: "A subtle tactics trap in the Open Ruy Lopez where White wins a piece due to an unpinned rook on the e-file.",
    punishmentExplanation: "Black plays 11...Qd7??, allowing White 12.Nxe6 fxe6 13.Rxe4! winning Black's e4 knight due to the pin on d5.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "Nf6", "O-O", "Nxe4", "d4", "b5", "Bb3", "d5", "dxe5", "Be6", "c3", "Be7", "Re1", "O-O", "Nd4", "Qd7", "Nxe6", "fxe6", "Rxe4"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bb5", explanation: "Ruy Lopez." },
      { moveSan: "a6", explanation: "Morphy Defense." },
      { moveSan: "Ba4", explanation: "White retreats bishop." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "O-O", explanation: "White castles." },
      { moveSan: "Nxe4", explanation: "Open Ruy Lopez." },
      { moveSan: "d4", explanation: "White strikes center." },
      { moveSan: "b5", explanation: "Black pushes b5." },
      { moveSan: "Bb3", explanation: "White retreats bishop." },
      { moveSan: "d5", explanation: "Black solidifies e4." },
      { moveSan: "dxe5", explanation: "White captures e5." },
      { moveSan: "Be6", explanation: "Black supports d5." },
      { moveSan: "c3", explanation: "White supports d4." },
      { moveSan: "Be7", explanation: "Black prepares castling." },
      { moveSan: "Re1", explanation: "White places rook on e-file." },
      { moveSan: "O-O", explanation: "Black castles." },
      { moveSan: "Nd4", explanation: "White leaps knight to d4." },
      { moveSan: "Qd7", isCriticalStep: true, explanation: "BLUNDER! Black aligns queen with d5 pawn." },
      { moveSan: "Nxe6", explanation: "White trades on e6." },
      { moveSan: "fxe6", explanation: "Black recaptures." },
      { moveSan: "Rxe4", isCriticalStep: true, explanation: "PIECE WIN! White captures e4 knight because Black's d5 pawn is pinned to the queen!" },
    ],
  },
];

