import { OpeningTrap } from "@/types/trap";

export const FAMOUS_TRAPS: OpeningTrap[] = [
  {
    id: "legals-trap",
    name: "Légal's Mate",
    openingName: "Italian Game",
    eco: "C41",
    side: "white",
    difficulty: "Beginner",
    description: "A legendary queen sacrifice in the Italian Game leading to a stunning knight and bishop checkmate on f7.",
    punishmentExplanation: "If Black greedily captures White's unprotected queen with 5...Bxd1??, White delivers checkmate with 6.Bxf7+ Ke7 7.Nd5#!",
    moves: ["e4", "e5", "Nf3", "d6", "Bc4", "Bg4", "Nc3", "g6", "Nxe5", "Bxd1", "Bxf7+", "Ke7", "Nd5#"],
    steps: [
      { moveSan: "e4", explanation: "White opens with the King's Pawn." },
      { moveSan: "e5", explanation: "Black responds symmetrically." },
      { moveSan: "Nf3", explanation: "White develops the knight attacking e5." },
      { moveSan: "d6", explanation: "Black defends with the Philidor Defense." },
      { moveSan: "Bc4", explanation: "White targets the weak f7 square." },
      { moveSan: "Bg4", explanation: "Black pins White's knight to the queen." },
      { moveSan: "Nc3", explanation: "White continues natural development." },
      { moveSan: "g6", explanation: "Black prepares to fianchetto, but neglects central king safety." },
      { moveSan: "Nxe5", isCriticalStep: true, explanation: "CRITICAL MOVE! White sacrifces the Queen on d1! If Black takes with 9...Bxd1??, White mates in two." },
      { moveSan: "Bxd1", explanation: "Black falls into the trap and greedily captures the Queen!" },
      { moveSan: "Bxf7+", explanation: "White checks the King, forcing it to e7." },
      { moveSan: "Ke7", explanation: "Black's King is forced to e7." },
      { moveSan: "Nd5#", isCriticalStep: true, explanation: "CHECKMATE! The two knights and bishop deliver a beautiful checkmate pattern!" },
    ],
  },
  {
    id: "noahs-ark-trap",
    name: "Noah's Ark Trap",
    openingName: "Ruy Lopez",
    eco: "C88",
    side: "black",
    difficulty: "Intermediate",
    description: "A famous trap in the Ruy Lopez where Black traps White's light-squared bishop on b3 using pawn pushes a6, b5, and c4.",
    punishmentExplanation: "White loses a full piece on b3 after Black's pawn push c4 traps the bishop with nowhere to escape.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6", "Ba4", "d6", "d4", "b5", "Bb3", "Nxd4", "Nxd4", "exd4", "Qxd4", "c5", "Qd5", "Be6", "Qc6+", "Bd7", "Qd5", "c4"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bb5", explanation: "Ruy Lopez opening." },
      { moveSan: "a6", explanation: "Morphy Defense forcing the bishop back." },
      { moveSan: "Ba4", explanation: "White retreats the bishop." },
      { moveSan: "d6", explanation: "Black prepares to push b5." },
      { moveSan: "d4", explanation: "White strikes in the center." },
      { moveSan: "b5", explanation: "Black expands on the queenside." },
      { moveSan: "Bb3", explanation: "White's bishop retreats to b3." },
      { moveSan: "Nxd4", explanation: "Black exchanges knights on d4." },
      { moveSan: "Nxd4", explanation: "White recaptures." },
      { moveSan: "exd4", explanation: "Black recaptures." },
      { moveSan: "Qxd4", isCriticalStep: true, explanation: "White recaptures with the Queen, but leaves the bishop susceptible to pawn pushes." },
      { moveSan: "c5", explanation: "Black attacks White's queen." },
      { moveSan: "Qd5", explanation: "White threatens a mate/rook fork on f7 & a8." },
      { moveSan: "Be6", explanation: "Black comfortably blocks." },
      { moveSan: "Qc6+", explanation: "White checks." },
      { moveSan: "Bd7", explanation: "Black blocks again." },
      { moveSan: "Qd5", explanation: "White's queen retreats." },
      { moveSan: "c4", isCriticalStep: true, explanation: "TRAPPED! Black pushes c4 and White's light-squared bishop on b3 has no escape squares!" },
    ],
  },
  {
    id: "stafford-gambit-trap",
    name: "Stafford Gambit Trap",
    openingName: "Petrov's Defense",
    eco: "C42",
    side: "black",
    difficulty: "Beginner",
    description: "An aggressive trap for Black involving rapid piece development and devastating tactical sacrifices against White's king.",
    punishmentExplanation: "White's kingside crumbles under Black's Ng4, Bc5, and Qh4 battery targeting f2 and h2.",
    moves: ["e4", "e5", "Nf3", "Nf6", "Nxe5", "Nc6", "Nxc6", "dxc6", "d3", "Bc5", "Bg5", "Nxe4", "Bxd8", "Bxf2+", "Ke2", "Bg4#"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nf6", explanation: "Petrov's Defense." },
      { moveSan: "Nxe5", explanation: "White captures on e5." },
      { moveSan: "Nc6", isCriticalStep: true, explanation: "Stafford Gambit! Black sacrifices a pawn for rapid piece development." },
      { moveSan: "Nxc6", explanation: "White accepts the knight trade." },
      { moveSan: "dxc6", explanation: "Black recaptures toward the center." },
      { moveSan: "d3", explanation: "White solidifies the e4 pawn." },
      { moveSan: "Bc5", explanation: "Black aims at f2." },
      { moveSan: "Bg5", explanation: "White pins Black's f6 knight." },
      { moveSan: "Nxe4!", isCriticalStep: true, explanation: "TACTICAL SACRIFICE! Black ignores the pin and sacrfices the Queen!" },
      { moveSan: "Bxd8", explanation: "White greedily accepts the Queen." },
      { moveSan: "Bxf2+", explanation: "Black checks on f2." },
      { moveSan: "Ke2", explanation: "White's King is forced to e2." },
      { moveSan: "Bg4#", isCriticalStep: true, explanation: "CHECKMATE! Black delivers checkmate with the light-squared bishop!" },
    ],
  },
  {
    id: "elephant-trap",
    name: "Elephant Trap",
    openingName: "Queen's Gambit Declined",
    eco: "D51",
    side: "black",
    difficulty: "Intermediate",
    description: "A subtle trap in the Queen's Gambit Declined where White attempts to win a pawn on d5 but loses a piece on d5.",
    punishmentExplanation: "If White plays 6.Nxd5?? thinking the c6 knight is pinned, Black plays 6...Nxd5! 7.Bxd8 Bb4+ winning White's queen back with an extra piece!",
    moves: ["d4", "d5", "c4", "e6", "Nc3", "Nf6", "Bg5", "Nbd7", "cxd5", "exd5", "Nxd5", "Nxd5", "Bxd8", "Bb4+", "Qd2", "Bxd2+", "Kxd2", "Kxd8"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn opening." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "c4", explanation: "Queen's Gambit." },
      { moveSan: "e6", explanation: "Queen's Gambit Declined." },
      { moveSan: "Nc3", explanation: "White develops Nc3." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "Bg5", explanation: "White pins Nf6." },
      { moveSan: "Nbd7", isCriticalStep: true, explanation: "The trap is set! Black sets a trap by developing Nbd7, appearing to leave d5 pinned." },
      { moveSan: "cxd5", explanation: "White takes on d5." },
      { moveSan: "exd5", explanation: "Black recaptures." },
      { moveSan: "Nxd5", isCriticalStep: true, explanation: "BLUNDER! White thinks d5 is pinned and captures the pawn." },
      { moveSan: "Nxd5!", explanation: "Black ignores the pin on the queen!" },
      { moveSan: "Bxd8", explanation: "White takes Black's queen." },
      { moveSan: "Bb4+", isCriticalStep: true, explanation: "FORCED QUEEN RECOVERY! Bb4+ forces Qd2." },
      { moveSan: "Qd2", explanation: "White is forced to block with the queen." },
      { moveSan: "Bxd2+", explanation: "Black takes White's queen." },
      { moveSan: "Kxd2", explanation: "White recaptures with the King." },
      { moveSan: "Kxd8", explanation: "Black recaptures the bishop on d8 and remains up a full piece!" },
    ],
  },
  {
    id: "lasker-trap",
    name: "Lasker Trap",
    openingName: "Albin Countergambit",
    eco: "D08",
    side: "black",
    difficulty: "Advanced",
    description: "A brilliant underpromotion trap in the Albin Countergambit featuring an underpromotion to a Knight with check on move 7!",
    punishmentExplanation: "7...fxg1=N+! promotes to a Knight with check, preventing White from trading queens and winning material.",
    moves: ["d4", "d5", "c4", "e5", "dxe5", "d4", "e3", "Bb4+", "Bd2", "dxe3", "Bxb4", "exf2+", "Ke2", "fxg1=N+", "Rxg1", "Bg4+"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn." },
      { moveSan: "d5", explanation: "Black plays d5." },
      { moveSan: "c4", explanation: "Queen's Gambit." },
      { moveSan: "e5", explanation: "Albin Countergambit!" },
      { moveSan: "dxe5", explanation: "White takes on e5." },
      { moveSan: "d4", explanation: "Black advances the d-pawn to d4." },
      { moveSan: "e3", explanation: "White tries to challenge d4." },
      { moveSan: "Bb4+", explanation: "Black checks on b4." },
      { moveSan: "Bd2", explanation: "White blocks with the bishop." },
      { moveSan: "dxe3", isCriticalStep: true, explanation: "Black sacrifices the bishop on b4!" },
      { moveSan: "Bxb4", explanation: "White greedily captures the bishop." },
      { moveSan: "exf2+", explanation: "Black checks on f2!" },
      { moveSan: "Ke2", explanation: "White's King steps to e2." },
      { moveSan: "fxg1=N+", isCriticalStep: true, explanation: "UNDERPROMOTION TO KNIGHT WITH CHECK! Promoting to Knight checks the King first!" },
      { moveSan: "Rxg1", explanation: "White's rook captures the knight." },
      { moveSan: "Bg4+", isCriticalStep: true, explanation: "QUEEN FORK! Black pins and wins White's queen!" },
    ],
  },
  {
    id: "fishing-pole-trap",
    name: "Fishing Pole Trap",
    openingName: "Ruy Lopez",
    eco: "C65",
    side: "black",
    difficulty: "Intermediate",
    description: "An aggressive trap for Black involving an unprovoked knight leap ng4 and h5 pawn sacrifice opening the h-file for checkmate.",
    punishmentExplanation: "White opens the h-file by capturing hxg4, allowing Black's rook to swarm the h-file with Qh4 and quick mate.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "O-O", "Ng4", "h3", "h5", "hxg4", "hxg4", "Ne1", "Qh4", "f3", "g3"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bb5", explanation: "Ruy Lopez." },
      { moveSan: "Nf6", explanation: "Berlin Defense." },
      { moveSan: "O-O", explanation: "White castles." },
      { moveSan: "Ng4", isCriticalStep: true, explanation: "Fishing Pole setup! Black leaps Ng4 inviting White to kick it with h3." },
      { moveSan: "h3", explanation: "White bites the bait and plays h3." },
      { moveSan: "h5", isCriticalStep: true, explanation: "Black defends the knight with h5, sacrificing the piece!" },
      { moveSan: "hxg4", explanation: "White captures the knight, opening the h-file." },
      { moveSan: "hxg4", explanation: "Black recaptures, opening the h-file for the h8 rook." },
      { moveSan: "Ne1", explanation: "White retreats the knight." },
      { moveSan: "Qh4", isCriticalStep: true, explanation: "Black's queen infiltrates on h4 threatening mate on h1!" },
      { moveSan: "f3", explanation: "White tries to make an escape square for the king." },
      { moveSan: "g3", isCriticalStep: true, explanation: "SEALED! Black plays g3, blocking the escape square and sealing White's king for mate on h1!" },
    ],
  },
  {
    id: "blackburne-shilling-gambit",
    name: "Blackburne Shilling Gambit",
    openingName: "Italian Game",
    eco: "C50",
    side: "black",
    difficulty: "Beginner",
    description: "A famous trap where Black offers an undefended pawn on e5, leading to a smothered mate or queen capture on c2.",
    punishmentExplanation: "White's greedy 4.Nxe5?? falls into 4...Qg5! threatening g2, e4, and f2.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nd4", "Nxe5", "Qg5", "Nxf7", "Qxg2", "Rf1", "Qxe4+", "Be2", "Nf3#"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn opening." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black plays Nc6." },
      { moveSan: "Bc4", explanation: "Italian Game." },
      { moveSan: "Nd4", isCriticalStep: true, explanation: "Black gambits e5 by moving Nd4!" },
      { moveSan: "Nxe5", explanation: "GREEDY BLUNDER! White takes the pawn on e5." },
      { moveSan: "Qg5", isCriticalStep: true, explanation: "COUNTERATTACK! Black attacks both the e5 knight and g2 pawn." },
      { moveSan: "Nxf7", explanation: "White forks Black's queen and rook." },
      { moveSan: "Qxg2", explanation: "Black takes g2, threatening White's rook." },
      { moveSan: "Rf1", explanation: "White saves the rook." },
      { moveSan: "Qxe4+", explanation: "Black checks on e4." },
      { moveSan: "Be2", explanation: "White blocks with the bishop." },
      { moveSan: "Nf3#", isCriticalStep: true, explanation: "SMOTHERED MATE! The knight on f3 delivers a beautiful smothered checkmate!" },
    ],
  },
  {
    id: "siberian-trap",
    name: "Siberian Trap",
    openingName: "Smith-Morra Gambit",
    eco: "B21",
    side: "black",
    difficulty: "Intermediate",
    description: "A deadly trap in the Sicilian Defense Smith-Morra Gambit leading to a queen-trapping checkmate pattern on h2.",
    punishmentExplanation: "White plays Bc4 and h3, allowing Black's Nd4 and Qc7 to threaten mate on h2 while trapping White's queen.",
    moves: ["e4", "c5", "d4", "cxd4", "c3", "dxc3", "Nxc3", "Nc6", "Nf3", "e6", "Bc4", "Qc7", "O-O", "Nf6", "Qe2", "Ng4", "h3", "Nd4"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn." },
      { moveSan: "c5", explanation: "Sicilian Defense." },
      { moveSan: "d4", explanation: "Smith-Morra Gambit." },
      { moveSan: "cxd4", explanation: "Black accepts." },
      { moveSan: "c3", explanation: "White offers c-pawn." },
      { moveSan: "dxc3", explanation: "Black accepts." },
      { moveSan: "Nxc3", explanation: "White develops." },
      { moveSan: "Nc6", explanation: "Black develops." },
      { moveSan: "Nf3", explanation: "White develops." },
      { moveSan: "e6", explanation: "Black solidifies." },
      { moveSan: "Bc4", explanation: "White targets f7." },
      { moveSan: "Qc7", explanation: "Black prepares battery." },
      { moveSan: "O-O", explanation: "White castles." },
      { moveSan: "Nf6", explanation: "Black develops Nf6." },
      { moveSan: "Qe2", explanation: "White moves queen." },
      { moveSan: "Ng4", explanation: "Black leaps Ng4." },
      { moveSan: "h3", explanation: "White kicks the knight with h3." },
      { moveSan: "Nd4", isCriticalStep: true, explanation: "DEVASTATING KNIGHT SACRIFICE! Nd4 attacks White's queen on e2 and threatens Nxf3+ followed by Qh2#!" },
    ],
  },
  {
    id: "englund-gambit-trap",
    name: "Englund Gambit Trap",
    openingName: "Englund Gambit",
    eco: "A40",
    side: "black",
    difficulty: "Beginner",
    description: "A fast tactical trap for Black against 1.d4 leading to a back-rank queen checkmate on c1.",
    punishmentExplanation: "White attempts to defend b2 with 6.Bc3??, allowing 6...Bb4! 7.Qd2 Bxc3 8.Qxc3 Qc1#!",
    moves: ["d4", "e5", "dxe5", "Nc6", "Nf3", "Qe7", "Bf4", "Qb4+", "Bd2", "Qxb2", "Bc3", "Bb4", "Qd2", "Bxc3", "Qxc3", "Qc1#"],
    steps: [
      { moveSan: "d4", explanation: "White plays 1.d4." },
      { moveSan: "e5", explanation: "Englund Gambit!" },
      { moveSan: "dxe5", explanation: "White accepts." },
      { moveSan: "Nc6", explanation: "Black attacks e5." },
      { moveSan: "Nf3", explanation: "White defends e5." },
      { moveSan: "Qe7", explanation: "Black doubles attack on e5." },
      { moveSan: "Bf4", explanation: "White defends e5." },
      { moveSan: "Qb4+", isCriticalStep: true, explanation: "QUEEN FORK! Checking the king and attacking b2 & f4!" },
      { moveSan: "Bd2", explanation: "White blocks check." },
      { moveSan: "Qxb2", explanation: "Black captures on b2." },
      { moveSan: "Bc3", explanation: "White defends the a1 rook." },
      { moveSan: "Bb4", isCriticalStep: true, explanation: "PIN! Black pins the c3 bishop to White's king!" },
      { moveSan: "Qd2", explanation: "White defends c3." },
      { moveSan: "Bxc3", explanation: "Black trades on c3." },
      { moveSan: "Qxc3", explanation: "White recaptures." },
      { moveSan: "Qc1#", isCriticalStep: true, explanation: "CHECKMATE! Back-rank checkmate on c1!" },
    ],
  },
  {
    id: "kieninger-trap",
    name: "Kieninger Trap",
    openingName: "Budapest Gambit",
    eco: "A52",
    side: "black",
    difficulty: "Intermediate",
    description: "A famous smothered mate trap in the Budapest Gambit ending with 8...Nd3#.",
    punishmentExplanation: "White plays 8.axb4?? expecting Black to lose a piece, but Black delivers a beautiful smothered checkmate with 8...Nd3#!",
    moves: ["d4", "Nf6", "c4", "e5", "dxe5", "Ng4", "Bf4", "Nc6", "Nf3", "Bb4+", "Nbd2", "Qe7", "a3", "Ngxe5", "axb4", "Nd3#"],
    steps: [
      { moveSan: "d4", explanation: "Queen's Pawn." },
      { moveSan: "Nf6", explanation: "Indian Defense." },
      { moveSan: "c4", explanation: "White pushes c4." },
      { moveSan: "e5", explanation: "Budapest Gambit!" },
      { moveSan: "dxe5", explanation: "White accepts." },
      { moveSan: "Ng4", explanation: "Black attacks e5." },
      { moveSan: "Bf4", explanation: "White defends." },
      { moveSan: "Nc6", explanation: "Black attacks e5 again." },
      { moveSan: "Nf3", explanation: "White defends." },
      { moveSan: "Bb4+", explanation: "Black checks on b4." },
      { moveSan: "Nbd2", explanation: "White blocks with Nbd2." },
      { moveSan: "Qe7", explanation: "Black attacks e5 a 3rd time." },
      { moveSan: "a3", explanation: "White kicks the bishop." },
      { moveSan: "Ngxe5", isCriticalStep: true, explanation: "TRAP SET! Black ignores the bishop and captures e5!" },
      { moveSan: "axb4", explanation: "GREEDY BLUNDER! White captures the bishop on b4." },
      { moveSan: "Nd3#", isCriticalStep: true, explanation: "SMOTHERED MATE! Nd3# checkmates White's king trapped by its own pawns!" },
    ],
  },
  {
    id: "mortimer-trap",
    name: "Mortimer Trap",
    openingName: "Ruy Lopez",
    eco: "C65",
    side: "white",
    difficulty: "Intermediate",
    description: "A clever counter-trap in the Berlin Ruy Lopez where White delivers a smothered mate with Nc4 and Nd6#.",
    punishmentExplanation: "If Black greedily plays 6...cxb5??, White mates with 7.Nd6#!",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6", "d3", "Ne7", "Nxe5", "c6", "Nc4", "cxb5", "Nd6#"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bb5", explanation: "Ruy Lopez." },
      { moveSan: "Nf6", explanation: "Berlin Defense." },
      { moveSan: "d3", explanation: "White solidifies e4." },
      { moveSan: "Ne7", explanation: "Mortimer Trap setup! Black leaves e5 undefended." },
      { moveSan: "Nxe5", explanation: "White captures e5." },
      { moveSan: "c6", explanation: "Black attacks the bishop on b5." },
      { moveSan: "Nc4", isCriticalStep: true, explanation: "COUNTER TRAP! White moves Nc4 threatening Nd6# smothered mate!" },
      { moveSan: "cxb5", explanation: "BLUNDER! Black captures the bishop, ignoring the smothered mate threat." },
      { moveSan: "Nd6#", isCriticalStep: true, explanation: "SMOTHERED MATE! White checkmates Black on d6!" },
    ],
  },
  {
    id: "fried-liver-attack",
    name: "Fried Liver Attack Trap",
    openingName: "Italian Game",
    eco: "C57",
    side: "white",
    difficulty: "Beginner",
    description: "An aggressive knight sacrifice on f7 forcing Black's king to walk into the open center under attack.",
    punishmentExplanation: "White sacrifices Nxf7, exposing Black's King to Qf3+ and Nc3 central pressure.",
    moves: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7", "Kxf7", "Qf3+", "Ke6", "Nc3"],
    steps: [
      { moveSan: "e4", explanation: "King's Pawn." },
      { moveSan: "e5", explanation: "Black plays e5." },
      { moveSan: "Nf3", explanation: "White attacks e5." },
      { moveSan: "Nc6", explanation: "Black defends Nc6." },
      { moveSan: "Bc4", explanation: "Italian Game." },
      { moveSan: "Nf6", explanation: "Two Knights Defense." },
      { moveSan: "Ng5", explanation: "White targets f7." },
      { moveSan: "d5", explanation: "Black blocks with d5." },
      { moveSan: "exd5", explanation: "White captures on d5." },
      { moveSan: "Nxd5", isCriticalStep: true, explanation: "Black recaptures with knight (Na5 is safer)." },
      { moveSan: "Nxf7", isCriticalStep: true, explanation: "KNIGHT SACRIFICE! White sacrifices on f7 forking Queen and Rook." },
      { moveSan: "Kxf7", explanation: "Black captures the knight." },
      { moveSan: "Qf3+", explanation: "White checks and attacks the d5 knight." },
      { moveSan: "Ke6", explanation: "Black's King is forced to e6 to defend d5." },
      { moveSan: "Nc3", explanation: "White piles pressure on the pinned d5 knight!" },
    ],
  },
];
